---
name: Build a docker image and push it to AWS ECR
on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
  
    name: Build and push
    
    env:
        PIPELINE_VARIABLE: abc
        IMAGE_NAME: 581851189815.dkr.ecr.us-east-2.amazonaws.com/rffsn-github-actions
        IMAGE_TAG: 0.0.1-SNAPSHOT
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing variables resolving
        run: |
            echo $PIPELINE_VARIABLE
            echo $IMAGE_NAME
            echo $IMAGE_TAG
            
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven (includes Docker image build)
        run: mvn --batch-mode --update-snapshots verify

#       - name: Build with Maven
#         run: mvn clean package
      
#      - name: Build image
#        run: |
#            docker build .

      - name: List images from local Github Docker
        run: |
            docker images
            
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Push to Amazon ECR docker registry
        run: |
            docker push $IMAGE_NAME:$IMAGE_TAG
            
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}