---
name: Build a docker image and push it to AWS ECR
on: [push]

jobs:
  build:
  
  
    name: Build and push
    env:
        PIPELINE_VARIABLE: abc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing variables resolving
        run: |
            echo $PIPELINE_VARIABLE
            
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'



#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots verify

#       - name: Build with Maven
#         run: mvn clean package
      
#      - name: Build image
#        run: |
#            docker build .

      - name: List images
        run: |
            docker images